# Generated by Django 3.2.5 on 2022-12-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_answer_class', '0001_initial'),
        ('class_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapterQuestionsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='', max_length=10, verbose_name='status')),
                ('lootbox_collected', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_quiz.classquiz')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_answer_class.quizansclass')),
            ],
            options={
                'verbose_name': 'user_chapter_question_record',
                'verbose_name_plural': 'user_chapter_question_records',
            },
        ),
    ]
