# Generated by Django 3.2.5 on 2023-03-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_chapter_question_record', '0002_userchapterquestionsrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchapterquestionsrecord',
            name='lootbox_collected',
        ),
    ]
