# Generated by Django 4.0.6 on 2023-01-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[('0', '0'), ('1', '1')], default='0', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer-support',
                'verbose_name_plural': 'customer-support',
            },
        ),
    ]
