# Generated by Django 4.0.6 on 2023-01-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersupport',
            name='status',
        ),
    ]
