# Generated by Django 4.0.6 on 2023-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0002_remove_customersupport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=1, verbose_name='status'),
        ),
    ]
