# Generated by Django 3.2.5 on 2023-02-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0003_customersupport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersupport',
            old_name='user_email',
            new_name='user',
        ),
    ]
