# Generated by Django 3.2.5 on 2023-02-07 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_support', '0004_rename_user_email_customersupport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
