# Generated by Django 3.2.5 on 2023-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_bytelesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='bytelesson',
            name='release_month',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
