# Generated by Django 4.0.6 on 2023-05-19 09:38

from django.db import migrations, models
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_bytelesson_release_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bytelesson',
            name='illustration_image',
            field=models.ImageField(blank=True, null=True, upload_to=lesson.models.class_directory_path),
        ),
    ]
