# Generated by Django 3.2.5 on 2023-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_bytelesson_illustration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bytelesson',
            name='activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
