# Generated by Django 4.0.6 on 2023-07-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0008_delete_byteclass'),
        ('lesson_attempt', '0004_delete_bytelessonattempt'),
        ('lesson', '0005_bytelesson_activated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ByteLesson',
        ),
    ]
