# Generated by Django 3.2.5 on 2023-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221017_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
