# Generated by Django 3.2.5 on 2022-12-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapter', '0001_initial'),
        ('class_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chapter.chapter')),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_quiz.classquiz')),
            ],
            options={
                'verbose_name': 'chapter_quiz',
                'verbose_name_plural': 'chapters_quiz',
            },
        ),
    ]
