# Generated by Django 3.2.5 on 2023-05-24 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_bytelesson_illustration_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_attempt', '0002_lessonattempt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByteLessonAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no-completed', 'no-completed'), ('completed', 'completed')], default='no-completed', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='byte_lesson_related', to='lesson.bytelesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='byte_lesson_attempt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
