# Generated by Django 4.0.6 on 2023-07-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_attempt', '0003_bytelessonattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ByteLessonAttempt',
        ),
    ]
