# Generated by Django 3.2.5 on 2022-12-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatisticStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_sats', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('potions', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('loot_boxes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('day_streak', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_statistics_status',
                'verbose_name_plural': 'users_statistics_status',
            },
        ),
        migrations.CreateModel(
            name='UserLeaderboardTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_value', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
