# Generated by Django 3.2.5 on 2023-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatisticstatus',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
