# Generated by Django 3.2.5 on 2023-01-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_text'),
        ('user_statistic_status', '0003_alter_userstatisticstatus_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatisticstatus',
            name='current_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
    ]
