# Generated by Django 3.2.5 on 2023-02-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0005_alter_userstatisticstatus_current_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatisticstatus',
            old_name='potions',
            new_name='heart',
        ),
    ]
