# Generated by Django 3.2.5 on 2023-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0006_rename_potions_userstatisticstatus_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticstatus',
            name='heart',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
    ]
