# Generated by Django 3.2.5 on 2023-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0007_alter_userstatisticstatus_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticstatus',
            name='total_sats',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
