# Generated by Django 3.2.5 on 2023-03-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0008_alter_userstatisticstatus_total_sats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatisticstatus',
            name='loot_boxes',
        ),
    ]
