# Generated by Django 3.2.5 on 2023-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0009_remove_userstatisticstatus_loot_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatisticstatus',
            name='current_class_byte',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
