# Generated by Django 3.2.5 on 2023-05-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0010_userstatisticstatus_current_class_byte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatisticstatus',
            name='current_class_byte',
        ),
    ]
