# Generated by Django 4.0.6 on 2023-07-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0011_remove_userstatisticstatus_current_class_byte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatisticstatus',
            old_name='total_sats',
            new_name='RBTC',
        ),
    ]
