# Generated by Django 4.0.6 on 2023-07-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0012_rename_total_sats_userstatisticstatus_rbtc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatisticstatus',
            name='day_streak',
        ),
        migrations.RemoveField(
            model_name='userstatisticstatus',
            name='heart',
        ),
    ]
