# Generated by Django 4.0.6 on 2023-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0013_remove_userstatisticstatus_day_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticstatus',
            name='RBTC',
            field=models.DecimalField(blank=True, decimal_places=10, default=50, max_digits=20, null=True),
        ),
    ]
