# Generated by Django 4.0.6 on 2023-07-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0014_alter_userstatisticstatus_rbtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticstatus',
            name='RBTC',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
