# Generated by Django 4.0.6 on 2023-07-17 15:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0015_alter_userstatisticstatus_rbtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticstatus',
            name='RBTC',
            field=models.DecimalField(blank=True, decimal_places=18, default=Decimal('50'), max_digits=20, null=True),
        ),
    ]
