# Generated by Django 4.0.6 on 2023-07-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistic_status', '0016_alter_userstatisticstatus_rbtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticstatus',
            name='RBTC',
            field=models.PositiveBigIntegerField(default=50),
        ),
    ]
