# Generated by Django 3.2.5 on 2022-12-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('correct_answer', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='', max_length=20, verbose_name='correct_answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer', to='class_quiz.classquiz')),
            ],
            options={
                'verbose_name': 'quiz_answer_class',
                'verbose_name_plural': 'quiz_answers_class',
            },
        ),
    ]
