name: Tickit-dev-CICD
on:
  push:
    branches: ["dev"]
  workflow_dispatch:
  
jobs:
  deploy:
    name: SSH and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd tick-it-FE
            git stash
            git pull
            yarn
            yarn build 
            pm2 restart 'tick-it-fe'
