name: tenjin_rootstock_all
description: Tenjin MVP for Rootstock hackathon.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: ^4.6.5
  flutter_secure_storage: ^6.0.0
  web3dart: ^2.7.0
  shared_preferences: ^2.2.0
  thor_devkit_dart: ^1.0.1
  google_fonts: ^5.1.0
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.3.1
  mobile_scanner: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
