name: Tenjin-backend-conda-env

dependencies:
  - python=3.10.4
  - pip=21.2.4
  - psycopg2

  - pip:
    - django==4.0.6
    - djangorestframework==3.13.1
    - djangorestframework-simplejwt==5.1.0
    - gunicorn==20.1.0
    - Pillow==9.0.1
    - flake8==4.0.1
    - drf-yasg==1.20.0
    - python-decouple==3.6
    - django-fullurl==1.3
    - django-filter==22.1
    - django-extensions==3.2.0
    - django-s3-storage==0.13.9
    - django-crispy-forms==1.14.0
    - django-link-shortener==0.5
    - dj-rest-auth==2.2.5
    - django-allauth==0.51.0
    - firebase-admin==6.0.1
    - celery==5.2.7
    - django-celery-beat==2.4.0
    - supervisor==4.2.5
    - celery[sqs]
    - boto3==1.24.78
    - supervisor==4.2.5
    - django-redis==5.2.0
    - hiredis==2.1.1
    - numpy==1.24.2
    - paramiko==3.0.0
    - plotly
    - web3==5.31.3



























