# Generated by Django 3.2.5 on 2023-05-02 09:14

import class_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to=class_app.models.class_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_class', models.ManyToManyField(to='class_app.Class')),
            ],
        ),
    ]
