# Generated by Django 3.2.5 on 2023-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_affiliatelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
