# Generated by Django 3.2.5 on 2023-05-05 10:36

import class_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_bytelesson'),
        ('class_app', '0003_affiliatelink_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByteClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(null=True)),
                ('illustration_image', models.ImageField(blank=True, null=True, upload_to=class_app.models.class_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.bytelesson')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
    ]
