# Generated by Django 3.2.5 on 2023-05-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_byteclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='byteclass',
            options={'verbose_name': 'byte_class', 'verbose_name_plural': 'byte_classes'},
        ),
    ]
