# Generated by Django 3.2.5 on 2023-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_alter_byteclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
