# Generated by Django 3.2.5 on 2023-05-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_bytelesson_release_month'),
        ('class_app', '0006_alter_affiliatelink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byteclass',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='byte', to='lesson.bytelesson'),
        ),
    ]
