# Generated by Django 3.2.5 on 2022-12-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
