# Generated by Django 3.2.5 on 2023-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230130_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_trails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
