# Generated by Django 3.2.5 on 2023-06-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
