# Generated by Django 3.2.5 on 2022-12-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_quiz', to='class_app.class', verbose_name='related class')),
            ],
            options={
                'verbose_name': 'class_quiz',
                'verbose_name_plural': 'class_quiz',
            },
        ),
    ]
