# Generated by Django 4.0.6 on 2023-07-10 16:1
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_quiz', '0002_classquiz_explination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classquiz',
            old_name='description',
            new_name='explination',
        ),
    ]
