# Generated by Django 4.0.6 on 2023-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_quiz', '0003_rename_description_classquiz_explination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classquiz',
            name='explination',
        ),
        migrations.AddField(
            model_name='classquiz',
            name='explanation',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
    ]
